apps/filetables/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, FileField, SubmitField
from wtforms.validators import Email, DataRequired


class FiletableForm(FlaskForm):
    type   = SelectField('Type', id='type', choices=[("product", "Product"), ("transaction", "Transaction")], render_kw={'class':'form-select type'})
    name   = StringField('Name', id='name', validators=[DataRequired()], render_kw={'class':'form-control name'})
    value  = StringField('Value', id='value', validators=[DataRequired()], render_kw={'class':'form-control value'})


class UploadFileForm(FlaskForm):
    file = FileField('File')
    submit = SubmitField('Upload File')

apps/filetables/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'filetables_blueprint',
    __name__,
    url_prefix=''
)

apps/filetables/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, request, jsonify, url_for, redirect, session
from sqlalchemy import or_

from apps import db

from apps.filetables import blueprint
from apps.home.models import Fileinfo, UploadFile
from apps.filetables.util import set_pagination

# from apps.filetables.forms import UploadFileForm


@blueprint.route('/file_list.html')
def uploadfiletables():
    if "ITEMS_PER_PAGE" not in session:
        session["ITEMS_PER_PAGE"] = 10

    search = request.args.get("search")
    if search:
        ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
        page = request.args.get('page', 1, type=int)

        total_items = UploadFile.query.count()
        print(total_items)
        paginated_data = UploadFile.query.filter(or_(UploadFile.name.like(search), UploadFile.value.like(search))).paginate(page, ITEMS_PER_PAGE, False)
    else:
        ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
        page = request.args.get('page', 1, type=int)

        total_items = UploadFile.query.count()
        paginated_data = UploadFile.query.paginate(page, ITEMS_PER_PAGE, False)

    pagination = set_pagination(page, ITEMS_PER_PAGE, total_items, paginated_data)


    return render_template('filetables/file_list.html',
                           file_list=paginated_data.items,
                           pagination=pagination,
                           segment="filetables")

@blueprint.route('/file_delete/<id>', methods=["DELETE"])
def file_delete(id):
    data = UploadFile.query.get(id)
    db.session.delete(data)
    db.session.commit()

    response = {'valid': 'success', 'message': 'Item deleted successfully', 'redirect_url': None}
    return jsonify(response)



# @blueprint.route('/file_list.html')
# def filetables():
#     if "ITEMS_PER_PAGE" not in session:
#         session["ITEMS_PER_PAGE"] = 10

#     search = request.args.get("search")
#     if search:
#         ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
#         page = request.args.get('page', 1, type=int)

#         total_items = Fileinfo.query.count()
#         paginated_data = Fileinfo.query.filter(or_(Fileinfo.name.like(search), Fileinfo.value.like(search))).paginate(page, ITEMS_PER_PAGE, False)
#     else:
#         ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
#         page = request.args.get('page', 1, type=int)

#         total_items = Fileinfo.query.count()
#         paginated_data = Fileinfo.query.paginate(page, ITEMS_PER_PAGE, False)

#     pagination = set_pagination(page, ITEMS_PER_PAGE, total_items, paginated_data)


#     return render_template('filetables/file_list.html',
#                            file_list=paginated_data.items,
#                            pagination=pagination,
#                            segment="filetables")


# @blueprint.route('/file_delete/<id>', methods=["DELETE"])
# def file_delete(id):
#     data = Fileinfo.query.get(id)
#     db.session.delete(data)
#     db.session.commit()

#     response = {'valid': 'success', 'message': 'Item deleted successfully', 'redirect_url': None}
#     return jsonify(response)


# @blueprint.route('/transactions_rows_per_page/<int:rows>')
# def transactions_rows_per_page(rows):
#     session["ITEMS_PER_PAGE"] = int(rows)
#     return redirect(url_for('datatables_blueprint.transactions'))


# @blueprint.route('/edit/<id>', methods=["GET", "POST"])
# def edit(id):

#     data = Data.query.get(id)
#     form = DatatableForm(obj=data)

#     if form.validate_on_submit():
#         form.populate_obj(data)

#         db.session.add(data)
#         db.session.commit()

#         return redirect(url_for('datatables_blueprint.transactions'))

#     return render_template('datatables/edit.html', form=form, data=data, segment="datatables")

apps/templates/filetables/file_list.html
{% extends "layouts/base.html" %}

{% block title %} Transactions {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Volt</a></li>
                <li class="breadcrumb-item active" aria-current="page">Transactions</li>
            </ol>
        </nav>
        <h2 class="h4">All Files</h2>
        <p class="mb-0">Your File analytics Dashboard</p>
    </div>

    <div class="d-block mb-md-0">
        <form id="form">
            <input id="media" type="file" name="file" /><br /><br />
            <input id="filesub" type="submit" name="file" value="Upload File" /><br />
        </form>

    </div>
</div>

<div class="table-settings mb-4">
    <div class="row align-items-center justify-content-between">
        <div class="col col-md-6 col-lg-3 col-xl-4">
            <div class="input-group me-2 me-lg-3 fmxw-400">

                <span class="input-group-text">
                    <svg class="icon icon-xs" x-description="Heroicon name: solid/search"
                        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"></path>
                    </svg>
                </span>
                <form action="{{ url_for('filetables_blueprint.uploadfiletables') }}" method="get">
                    <input type="text" name="search" class="form-control" placeholder="Search filetable">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="card card-body border-0 shadow table-wrapper table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="border-gray-200">#</th>
                <th class="border-gray-200">Filename</th>
                <th class="border-gray-200">Filesize</th>
                <th class="border-gray-200">File Type</th>
                <th class="border-gray-200">Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- Item -->
            {% for file in file_list %}
            <tr class="item-row">
                <td><span class="fw-bold">{{ file.id }}</span></td>
                <td><span class="fw-normal">{{ file.filename }}</span></td>
                <td><span class="fw-normal">{{ file.filesize }}</span></td>
                <td><span class="fw-normal">{{ file.filetype }}</span></td>
                <td>
                    <!-- <a class="btn btn-sm btn-secondary" href="{{ url_for('datatables_blueprint.edit', id=file.id) }}">Edit</a> -->
                    <a class="btn btn-sm btn-danger delete_item"
                        data-href="{{ url_for('filetables_blueprint.file_delete', id=file.id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% include 'filetables/pagination.html' %}
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
    const form = document.getElementById("form");
    form.addEventListener("submit", (event) => {
        console.log("Submit Triggered")
        event.preventDefault();
        const fileInput = document.querySelector("#media");
        const formData = new FormData();

        formData.append("file", fileInput.files[0]);

        const options = {
            method: "POST",
            body: formData,
        };

        fetch("/api/file_upload", options)
            .then((response) => {
                return response.json();
            })
            .then((data) => {
                console.log(data);
            })
            .catch((error) => {
                console.log(error);
            });
        fileInput.value="";
        // location.reload(true);
    });
</script>

{% endblock javascripts %}

apps/templates/filetables/pagination.html
{% if pagination.has_prev or pagination.has_next %}
<div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
  <nav aria-label="Page navigation example">
    <ul class="pagination mb-0">
      {% if pagination.has_prev %}
      <li class="page-item">
        <a class="page-link" href="?page={{ pagination.page - 1 }}">Previous</a>
      </li>
      {% endif %}
      {% for page_num in pagination.page_range %}
        {% if page_num == pagination.page %}
          <li class="page-item active">
            <a class="page-link" href="">{{page_num}}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{page_num}}</a>
          </li>
        {% endif %}
      {% endfor%}
      {% if pagination.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ pagination.page + 1 }}">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  <div class="fw-normal small mt-4 mt-lg-0">Showing <b>{{pagination.item_per_page}}</b> out of <b>{{pagination.total_items}}</b> entries</div>
</div>
{% endif %}