apps/datatables/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, FileField
from wtforms.validators import Email, DataRequired


class DatatableForm(FlaskForm):
    type   = SelectField('Type', id='type', choices=[("product", "Product"), ("transaction", "Transaction")], render_kw={'class':'form-select type'})
    name   = StringField('Name', id='name', validators=[DataRequired()], render_kw={'class':'form-control name'})
    value  = StringField('Value', id='value', validators=[DataRequired()], render_kw={'class':'form-control value'})

apps/datatables/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'datatables_blueprint',
    __name__,
    url_prefix=''
)

apps/datatables/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, request, jsonify, url_for, redirect, session
from sqlalchemy import or_

from apps import db

from apps.datatables import blueprint
from apps.home.models import Data
from apps.datatables.util import set_pagination
from apps.datatables.forms import DatatableForm


@blueprint.route('/transactions.html')
def transactions():

    if "ITEMS_PER_PAGE" not in session:
        session["ITEMS_PER_PAGE"] = 10

    search = request.args.get("search")
    if search:
        ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
        page = request.args.get('page', 1, type=int)

        total_items = Data.query.count()
        paginated_data = Data.query.filter(or_(Data.name.like(search), Data.value.like(search))).paginate(page, ITEMS_PER_PAGE, False)
    else:
        ITEMS_PER_PAGE = session["ITEMS_PER_PAGE"]
        page = request.args.get('page', 1, type=int)

        total_items = Data.query.count()
        paginated_data = Data.query.paginate(page, ITEMS_PER_PAGE, False)

    pagination = set_pagination(page, ITEMS_PER_PAGE, total_items, paginated_data)

    return render_template('datatables/list.html',
                           data_list=paginated_data.items,
                           pagination=pagination,
                           segment="datatables")

@blueprint.route('/transactions_rows_per_page/<int:rows>')
def transactions_rows_per_page(rows):
    session["ITEMS_PER_PAGE"] = int(rows)
    return redirect(url_for('datatables_blueprint.transactions'))


@blueprint.route('/edit/<id>', methods=["GET", "POST"])
def edit(id):

    data = Data.query.get(id)
    form = DatatableForm(obj=data)

    if form.validate_on_submit():
        form.populate_obj(data)

        db.session.add(data)
        db.session.commit()

        return redirect(url_for('datatables_blueprint.transactions'))

    return render_template('datatables/edit.html', form=form, data=data, segment="datatables")


@blueprint.route('/edit_row/<id>', methods=["GET", "PUT"])
def edit_row(id):

    data = Data.query.get(id)

    # handle PUT request
    if request.method == "PUT":

        # check if any of 'value' or 'name' fields are available for update
        new_data_available = False

        if "value" in request.form:
            data.value = request.form["value"]
            new_data_available = True
        if "name" in request.form:
            data.name = request.form["name"]
            new_data_available = True

        if new_data_available:

            db.session.add(data)
            db.session.commit()

            updated_data = Data.query.get(id)
            edit_row = render_template('datatables/edit_row.html', form=None, data=updated_data)
            return jsonify({'valid': 'success', 'message': 'Transaction saved successfully', 'edit_row': edit_row})

        updated_data = Data.query.get(id)
        edit_row = render_template('datatables/edit_row.html', form=None, data=updated_data)
        return jsonify({'valid': 'warning', 'message': 'Error Occurred. Please try again.', 'edit_row': edit_row})

    data = Data.query.get(id)
    form = DatatableForm(obj=data)

    return render_template('datatables/edit_row.html', form=form, data=data)


@blueprint.route('/row_details/<id>')
def row_details(id):
    data = Data.query.get(id)

    return render_template('datatables/edit_row.html', form=None, data=data)


@blueprint.route('/row_delete/<id>', methods=["DELETE"])
def row_delete(id):
    data = Data.query.get(id)
    db.session.delete(data)
    db.session.commit()

    response = {'valid': 'success', 'message': 'Item deleted successfully', 'redirect_url': None}
    return jsonify(response)


@blueprint.route('/row_delete/<id>/single', methods=["DELETE"])
def row_delete_single(id):
    data = Data.query.get(id)
    db.session.delete(data)
    db.session.commit()

    redirect_url = url_for('datatables_blueprint.transactions')
    response = {'valid': 'success', 'message': 'Item deleted successfully', 'redirect_url': redirect_url}
    return jsonify(response)

apps/templates/datatables/edit.html
{% extends "layouts/base.html" %}

{% block title %} Transactions {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
      <div class="d-block mb-4 mb-md-0">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
              <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                  <li class="breadcrumb-item">
                      <a href="#">
                          <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                      </a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Volt</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Transactions</li>
              </ol>
          </nav>
          <h2 class="h4">Edit Transaction</h2>
          <p class="mb-0">Your web analytics dashboard template.</p>
      </div>
  </div>
  
  <div class="table-settings mb-4">
      <div class="row align-items-center justify-content-between">
          <div class="col col-md-6 col-lg-3 col-xl-4">
              <div class="input-group me-2 me-lg-3 fmxw-400">
                
                  <span class="input-group-text">
                      <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                      </svg>
                  </span>
                  <form action="{{ url_for('datatables_blueprint.transactions') }}" method="get">
                  <input type="text" name="search"  class="form-control" placeholder="Search datatable">
                </form>
              </div>
          </div>
          <div class="col-4 col-md-2 col-xl-1 ps-md-0 text-end">
              <div class="dropdown">
                  <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                      <span class="visually-hidden">Toggle Dropdown</span>
                  </button>
                  <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0">
                      <span class="small ps-3 fw-bold text-dark">Show</span>
                      <a class="dropdown-item d-flex align-items-center fw-bold" href="#">10 <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg></a>
                      <a class="dropdown-item fw-bold" href="#">20</a>
                      <a class="dropdown-item fw-bold rounded-bottom" href="#">30</a>
                  </div>
              </div>
          </div>
      </div>
  </div>
  
  <div class="row item-row">
        <div class="col-12">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <h2 class="h5 mb-4">Edit Data</h2>
                <form action="{{ url_for('datatables_blueprint.edit', id=data.id)}}" method="post">
                    {{ form.csrf_token }}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div>{{ form.name.label }}{{ form.name }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>{{ form.value.label }}{{ form.value }}</div>
                        </div>
                    </div>

                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-danger delete_item"
                           data-href="{{ url_for('datatables_blueprint.row_delete_single', id=data.id) }}">Delete</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/datatables/edit_row.html
{% if form %}
    <td><span class="fw-bold">{{ data.id }}</span></td>
    <form>
        {{ form.csrf_token }}
        <td>{{ form.name }}</td>
        <td>{{ form.value }}</td>
    </form>
    <td><span class="fw-bold">{{ data.ts.strftime('%d %b %Y') }}</span></td>
    <td>
        <button class="btn-sm btn-warning cancel_form">Cancel</button>
        <button class="btn-sm btn-success save_form">Save</button>
    </td>
{% else %}
    <td><span class="fw-bold">{{ data.id }}</span></td>
    <td><span class="fw-normal">{{ data.name }}</span></td>
    <td><span class="fw-normal">{{ data.value }}</span></td>
    <td><span class="fw-normal">${{ data.ts.strftime('%d %b %Y') }}</span></td>
    <td>
        <a class="btn btn-sm btn-secondary" href="#">Edit</a>
        <a class="btn btn-sm btn-danger" href="#">Delete</a>
    </td>
{% endif %}

apps/templates/datatables/list.html
{% extends "layouts/base.html" %}

{% block title %} Transactions {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
      <div class="d-block mb-4 mb-md-0">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
              <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                  <li class="breadcrumb-item">
                      <a href="#">
                          <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                      </a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Volt</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Transactions</li>
              </ol>
          </nav>
          <h2 class="h4">All Transactions</h2>
          <p class="mb-0">Your web analytics dashboard template.</p>
      </div>
  </div>
  
  <div class="table-settings mb-4">
      <div class="row align-items-center justify-content-between">
          <div class="col col-md-6 col-lg-3 col-xl-4">
              <div class="input-group me-2 me-lg-3 fmxw-400">
                
                  <span class="input-group-text">
                      <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                      </svg>
                  </span>
                  <form action="{{ url_for('datatables_blueprint.transactions') }}" method="get">
                  <input type="text" name="search"  class="form-control" placeholder="Search datatable">
                </form>
              </div>
          </div>
          <div class="col-4 col-md-2 col-xl-1 ps-md-0 text-end">
              <div class="dropdown">
                  <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                      <span class="visually-hidden">Toggle Dropdown</span>
                  </button>
                  <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0">
                      <span class="small ps-3 fw-bold text-dark">Show</span>
                      <a class="dropdown-item d-flex align-items-center fw-bold" href="{{ url_for('datatables_blueprint.transactions_rows_per_page', rows=10) }}">10 {% if pagination.item_per_page == 10 %} <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>{% endif %}</a>
                      <a class="dropdown-item fw-bold" href="{{ url_for('datatables_blueprint.transactions_rows_per_page', rows=20) }}">20 {% if pagination.item_per_page == 20 %} <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>{% endif %}</a>
                      <a class="dropdown-item fw-bold rounded-bottom" href="{{ url_for('datatables_blueprint.transactions_rows_per_page', rows=30) }}">30 {% if pagination.item_per_page == 30 %} <svg class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>{% endif %}</a>
                  </div>
              </div>
          </div>
      </div>
  </div>
  
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
      <table class="table table-hover">
          <thead>
              <tr>
                  <th class="border-gray-200">#</th>
                  <th class="border-gray-200">Name</th>
                  <th class="border-gray-200">Value</th>
                  <th class="border-gray-200">Timestamp</th>
                  <th class="border-gray-200">Actions</th>
              </tr>
          </thead>
          <tbody>
              <!-- Item -->
              {% for data in data_list %}
              <tr class="item-row" data-edit="{{ url_for('datatables_blueprint.edit_row', id=data.id) }}" data-detail="{{ url_for('datatables_blueprint.row_details', id=data.id) }}">
                  <td><span class="fw-bold">{{ data.id }}</span></td>
                  <td><span class="fw-normal">{{ data.name }}</span></td>
                  <td><span class="fw-normal">${{ data.value }}</span></td>
                  <td><span class="fw-normal">{{ data.ts | ctime }}</span></td>
                  <td>
                    <a class="btn btn-sm btn-secondary" href="{{ url_for('datatables_blueprint.edit', id=data.id) }}">Edit</a>
                    <a class="btn btn-sm btn-danger delete_item"  data-href="{{ url_for('datatables_blueprint.row_delete', id=data.id) }}">Delete</a>
                  </td>
              </tr>
              {% endfor %}

          </tbody>
      </table>
      {% include 'datatables/pagination.html' %}
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/datatables/pagination.html
{% if pagination.has_prev or pagination.has_next %}
<div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
  <nav aria-label="Page navigation example">
    <ul class="pagination mb-0">
      {% if pagination.has_prev %}
      <li class="page-item">
        <a class="page-link" href="?page={{ pagination.page - 1 }}">Previous</a>
      </li>
      {% endif %}
      {% for page_num in pagination.page_range %}
        {% if page_num == pagination.page %}
          <li class="page-item active">
            <a class="page-link" href="">{{page_num}}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{page_num}}</a>
          </li>
        {% endif %}
      {% endfor%}
      {% if pagination.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ pagination.page + 1 }}">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  <div class="fw-normal small mt-4 mt-lg-0">Showing <b>{{pagination.item_per_page}}</b> out of <b>{{pagination.total_items}}</b> entries</div>
</div>
{% endif %}